export const FETCH_ELECTRONICS_REQUEST = 'FETCH_ELECTRONICS_REQUEST';
export const FETCH_ELECTRONICS_SUCCESS = 'FETCH_ELECTRONICS_SUCCESS';
export const FETCH_ELECTRONICS_FAILURE = 'FETCH_ELECTRONICS_FAILURE';
export const DELETE_ELECTRONICS = 'DELETE_ELECTRONICS';